# Generated by Django 5.2.3 on 2025-07-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cdd_users',
            table='CDD_Users',
        ),
    ]
