# Generated by Django 5.2.3 on 2025-07-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cdd_users_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdd_users',
            options={'verbose_name_plural': 'CDD_Users'},
        ),
        migrations.AlterModelTable(
            name='cdd_users',
            table=None,
        ),
    ]
