# Generated by Django 5.2.3 on 2025-07-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cdd_users_options_alter_cdd_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('handover_id', models.CharField(editable=False, max_length=60, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('shift', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=10)),
                ('dispatcher_name', models.CharField(max_length=100)),
                ('chief_duty_name', models.CharField(max_length=100)),
                ('shift_highlight', models.TextField()),
                ('non_standard_flights', models.JSONField(default=list)),
                ('naifr', models.JSONField(default=list)),
                ('aog', models.JSONField(default=list)),
                ('comat', models.JSONField(default=list)),
                ('fob_created', models.BooleanField()),
                ('remarked_added', models.BooleanField()),
                ('fuel_payload', models.JSONField(default=list)),
                ('weather_issues', models.JSONField(default=list)),
                ('notams', models.JSONField(default=list)),
                ('mels', models.JSONField(default=list)),
                ('nvb_tickets', models.JSONField(default=list)),
                ('tmi', models.JSONField(default=list)),
                ('enroute_weather', models.TextField()),
                ('require_cdd_followup', models.TextField()),
                ('misc', models.TextField()),
                ('it_issues', models.TextField()),
                ('procedural_changes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Handovers',
            },
        ),
    ]
