# Generated by Django 5.2.3 on 2025-07-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_handover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handover',
            old_name='enroute_weather',
            new_name='cdd_followup',
        ),
        migrations.RenameField(
            model_name='handover',
            old_name='fob_created',
            new_name='comat_request_created',
        ),
        migrations.RenameField(
            model_name='handover',
            old_name='require_cdd_followup',
            new_name='enroute_weather_pirep',
        ),
        migrations.RenameField(
            model_name='handover',
            old_name='remarked_added',
            new_name='fob_co_notam_created',
        ),
        migrations.RenameField(
            model_name='handover',
            old_name='fuel_payload',
            new_name='fuel_payload_critical_flights',
        ),
        migrations.RenameField(
            model_name='handover',
            old_name='mels',
            new_name='operational_notams',
        ),
        migrations.RenameField(
            model_name='handover',
            old_name='notams',
            new_name='performance_mels',
        ),
        migrations.RenameField(
            model_name='handover',
            old_name='shift_highlight',
            new_name='shift_highlights',
        ),
    ]
