# Generated by Django 5.2.3 on 2025-07-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_enroute_weather_handover_cdd_followup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handover',
            name='aog',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='cdd_followup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='comat',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='comat_request_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='handover',
            name='enroute_weather_pirep',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='fob_co_notam_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='handover',
            name='fuel_payload_critical_flights',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='it_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='misc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='naifr',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='non_standard_flights',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='nvb_tickets',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='operational_notams',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='performance_mels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='procedural_changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='tmi',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='handover',
            name='weather_issues',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
