# Generated by Django 5.2.3 on 2025-07-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_handover_aog_alter_handover_cdd_followup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handover',
            old_name='created_at',
            new_name='modified_at',
        ),
    ]
