# Generated by Django 5.2.3 on 2025-07-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_created_at_handover_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handover',
            name='date',
            field=models.DateField(),
        ),
    ]
